Repository cozuya/secret-hitler, pull requests merged in 2019-03, with the labels that each got.

#1345 Adds Refresh Button to Moderation Tab
  src/frontend-scripts/components/section-main/Moderation.jsx
  src/scss/moderation.scss
  src/scss/style-dark.scss
Labels: testing

#1348 Game Icons Mod Tools (v2)
  routes/socket/user-requests.js
  src/frontend-scripts/components/section-main/Moderation.jsx
  src/frontend-scripts/components/section-main/moderation.test.js
  src/scss/style-dark.scss
Labels: testing

#1361 Fixes Profile Bio from being force deleted when editing
  src/frontend-scripts/components/section-main/Profile.jsx
Labels: testing, under review

#1360 Various Silent Game Mode Fixes
  routes/socket/user-events.js
  src/frontend-scripts/components/section-main/Gamechat.jsx
Labels: testing

#1365 1.4 Changelog
  package.json
  routes/index.js
  src/frontend-scripts/components/section-main/Changelog.jsx
  version.js
  views/page-changelog.pug
  views/page-home.pug
Labels: on-hold

#1366 April Fools!
  routes/socket/game/policy-powers.js
  src/frontend-scripts/components/section-main/Gamechat.jsx
  src/frontend-scripts/components/section-right/Playerlist.jsx
  src/frontend-scripts/constants.js
Labels: ready for merge
