Repository cozuya/secret-hitler, pull requests merged in 2020-06, with the labels that each got.

#1526 Disallow sending empty messages
  routes/socket/user-events.js
Labels: on-hold, ready for merge

#1559 max username length increased to 16 from 12
  routes/accounts.js
  src/frontend-scripts/account.js
  src/scss/rightsidebar.scss
  src/scss/style-dark.scss
Labels: on-hold, ready for merge

#1531 Shorten Game URIs
  routes/socket/user-events.js
  src/frontend-scripts/components/section-main/Gamechat.jsx
Labels: on-hold, ready for merge

#1593 Dont show forcevote in chat
  routes/socket/user-events.js
Labels: on-hold, ready for merge

#1536 ELO Housekeeping
  routes/socket/util.js
Labels: on-hold, ready for merge

#1589 Resolves #1578
  routes/socket/game/end-game.js
Labels: on-hold, ready for merge

#1594 #1319 added options to disable observer chat during the game and/or lobby
  docs/model-info.txt
  routes/socket/user-events.js
  src/frontend-scripts/components/App.jsx
  src/frontend-scripts/components/section-main/Creategame.jsx
  src/frontend-scripts/components/section-main/Gamechat.jsx
Labels: needs changes

#1638 Update this to match recent wiki changes by coz
  views/page-home.pug
Labels: good for first timers

#1639 Timer improvements
  docs/sounds.txt
  public/sounds/pack1/clockTick.mp3
  src/frontend-scripts/components/section-main/Tracks.jsx
  src/frontend-scripts/components/section-main/tracks.test.js
  src/scss/tracks.scss
Labels: testing, under review

#1640 Keep chat anonymized when user stands up
  src/frontend-scripts/components/section-main/Gamechat.jsx
Labels: testing, under review
