Repository cozuya/secret-hitler, pull requests merged in 2020-07, with the labels that each got.

#1651 Fix serveral typos
  routes/account-verification-email.template
  views/layout.pug
  views/page-about.pug
  views/page-changelog.pug
Labels: under review

#1649 Update accounts.js
  routes/accounts.js
Labels: under review

#1657 show games a player is seated in at top of games list
  src/frontend-scripts/components/section-main/GamesList.jsx
Labels: under review

#1653 Fix and re-add emote button.
  src/frontend-scripts/components/section-main/Gamechat.jsx
  src/frontend-scripts/components/section-right/Generalchat.jsx
  src/frontend-scripts/emotes.js
Labels: testing, under review

#1647 Creates a contributing tutorial
  CONTRIBUTING_TUTORIAL.md
Labels: needs changes

#1671 Update user-events.js
  routes/socket/user-events.js
Labels: discussion
