Repository cozuya/secret-hitler, pull requests merged in 2020-09, with the labels that each got.

#1707 Max1071 to u
  views/page-tou.pug
Labels: under review

#1705 Bruno
  src/frontend-scripts/constants.js
  src/frontend-scripts/node-constants.js
  src/scss/players.scss
  src/scss/profile.scss
  src/scss/style-dark.scss
Labels: under review

#1702 Send remaining deck order when game is remade
  routes/socket/user-events.js
Labels: under review

#1698 Added season 9 top10
  src/frontend-scripts/components/section-main/Changelog.jsx
Labels: under review

#1695 don't render the emote helper if allEmotes isn't loaded
  src/frontend-scripts/components/section-main/Gamechat.jsx
Labels: under review

#1693 Should fix things.
  routes/socket/game/election.js
  routes/socket/game/policy-powers.js
Labels: testing, under review

#1692 More 10minutemail alts
  utils/disposableEmails.js
Labels: under review

#1687 Better sticky note
  src/frontend-scripts/components/App.jsx
  src/frontend-scripts/components/section-main/GamesList.jsx
  src/frontend-scripts/components/section-main/Main.jsx
  src/frontend-scripts/components/section-main/gameslist.test.js
  src/frontend-scripts/components/section-right/Generalchat.jsx
  src/frontend-scripts/components/section-right/generalchat.test.js
  src/scss/rightsidebar.scss
Labels: testing, under review

#1690 Make replay links in bio open in the current tab
  src/frontend-scripts/components/section-main/Creategame.jsx
  src/frontend-scripts/components/section-main/Profile.jsx
Labels: under review

#1679 Update Settings.jsx
  src/frontend-scripts/components/section-main/Settings.jsx
Labels: under review

#1682 Fixes #1602 - Status bar disappearing
  routes/socket/user-events.js
Labels: under review

#1681 Fixing #1618 - Wrong side winning
  routes/socket/game/election.js
Labels: testing, under review

#1673 Make icons more consistent
  src/frontend-scripts/components/section-main/DisplayLobbies.jsx
  src/frontend-scripts/components/section-main/Tracks.jsx
Labels: under review

#1676 Fix #1675
  routes/socket/user-events.js
Labels: testing, under review

#1699 Allows signups to be sorted by varying columns
  src/frontend-scripts/components/section-main/Signups.jsx
Labels: testing, under review

#1674 User popup
  .babelrc
  package.json
  routes/socket/routes.js
  routes/socket/user-events.js
  src/frontend-scripts/components/reusable/UserPopup.jsx
  src/frontend-scripts/components/section-main/Players.jsx
  src/frontend-scripts/components/section-main/Reports.jsx
  src/frontend-scripts/components/section-right/Playerlist.jsx
  src/scss/players.scss
  yarn.lock
Labels: testing, under review

#1704 Update models.js
  routes/socket/models.js
Labels: needs changes

#1732 Unbanning certain words
  iso/blacklistwords.js
Labels: needs changes
